spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BlazCulina1911/external-config
          default-label: master
          clone-on-start: true
          force-pull: true
          timeout: 5
          basedir: external-config
          search-paths: /*

server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5